server:
  port: 8084
spring:
  application:
    name: analytics
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
wsa:
  storage: inmemory
management:
  endpoints:
    web:
      exposure:
        include: health,info
