server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /api/gateway/v1/events/ingest {
        proxy_pass http://gateway:8081/v1/events/ingest;
        proxy_set_header Host $host;
    }
    location /api/gateway/ {
        proxy_pass http://gateway:8081/;
        proxy_set_header Host $host;
    }
    location /api/analytics/ {
        proxy_pass http://analytics:8084/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}
